#!/bin/bash

set -euo pipefail

echo "
REACT_APP_PAGE_SIZE=20
REACT_APP_API_BASE_URL=http://localhost:8000
# REACT_APP_API_CREDENTIALS=omit
# REACT_APP_ALLOW_USER_PASSWORD_LOGIN=true
REACT_APP_IDLE_SECONDS_LOGOUT=600
REACT_APP_GOOGLE_ANALYTICS_CODE=
REACT_APP_SENTRY_DSN=
"
