-- Deploy sepraps:create_tables_payments to pg

BEGIN;
--
-- Create model Comment
--
CREATE TABLE "comment" ("created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "active" boolean NOT NULL, "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "text" text NOT NULL, "created_by_id" bigint NOT NULL, "updated_by_id" bigint NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "payment" ("created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "active" boolean NOT NULL, "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "expected_fixed_amount" numeric(20, 2) NULL, "expected_variable_amount" numeric(20, 2) NULL, "expected_total_amount" numeric(20, 2) NULL, "expected_payment_date" date NULL, "paid_fixed_amount" numeric(20, 2) NULL, "paid_variable_amount" numeric(20, 2) NULL, "paid_total_amount" numeric(20, 2) NULL, "status" varchar(20) NOT NULL, "payment_date" date NULL);
CREATE TABLE "payment_comments" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "payment_id" integer NOT NULL, "comment_id" integer NOT NULL);
--
-- Add field awarding_budget_min to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "awarding_budget_min" numeric(20, 2) NULL;
--
-- Add field bid_request_budget_min to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "bid_request_budget_min" numeric(20, 2) NULL;
--
-- Add field payment_criteria_type to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "payment_criteria_type" varchar(20) DEFAULT 'variable' NOT NULL;
ALTER TABLE "construction_contract" ALTER COLUMN "payment_criteria_type" DROP DEFAULT;
--
-- Add field payment_frequency_type to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "payment_frequency_type" varchar(20) DEFAULT 'mensual' NOT NULL;
ALTER TABLE "construction_contract" ALTER COLUMN "payment_frequency_type" DROP DEFAULT;
--
-- Add field total_amount_type to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "total_amount_type" varchar(20) DEFAULT 'fijo' NOT NULL;
ALTER TABLE "construction_contract" ALTER COLUMN "total_amount_type" DROP DEFAULT;
--
-- Add field active to fieldreport
--
ALTER TABLE "field_report" ADD COLUMN "active" boolean DEFAULT true NOT NULL;
ALTER TABLE "field_report" ALTER COLUMN "active" DROP DEFAULT;
--
-- Add field active to fieldreportproject
--
ALTER TABLE "field_report_project" ADD COLUMN "active" boolean DEFAULT true NOT NULL;
ALTER TABLE "field_report_project" ALTER COLUMN "active" DROP DEFAULT;
--
-- Add field active to fieldreportprojectactivity
--
ALTER TABLE "field_report_project_activity" ADD COLUMN "active" boolean DEFAULT true NOT NULL;
ALTER TABLE "field_report_project_activity" ALTER COLUMN "active" DROP DEFAULT;
--
-- Add field active to provider
--
ALTER TABLE "provider" ADD COLUMN "active" boolean DEFAULT true NOT NULL;
ALTER TABLE "provider" ALTER COLUMN "active" DROP DEFAULT;
--
-- Create model Product
--
CREATE TABLE "product" ("created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "active" boolean NOT NULL, "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "status" varchar(20) NULL, "product_date" date NULL, "created_by_id" bigint NOT NULL, "featured_document_id" integer NULL, "featured_image_id" integer NULL, "folder_id" integer NULL, "payment_id" integer NULL, "updated_by_id" bigint NOT NULL);
--
-- Add field contract to payment
--
ALTER TABLE "payment" ADD COLUMN "contract_id" integer NULL CONSTRAINT "payment_contract_id_4abcd408_fk_construction_contract_id" REFERENCES "construction_contract"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_contract_id_4abcd408_fk_construction_contract_id" IMMEDIATE;
--
-- Add field created_by to payment
--
ALTER TABLE "payment" ADD COLUMN "created_by_id" bigint NOT NULL CONSTRAINT "payment_created_by_id_0a1fb28a_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_created_by_id_0a1fb28a_fk_users_user_id" IMMEDIATE;
--
-- Add field featured_document to payment
--
ALTER TABLE "payment" ADD COLUMN "featured_document_id" integer NULL CONSTRAINT "payment_featured_document_id_56f84645_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_featured_document_id_56f84645_fk_media_node_id" IMMEDIATE;
--
-- Add field featured_image to payment
--
ALTER TABLE "payment" ADD COLUMN "featured_image_id" integer NULL CONSTRAINT "payment_featured_image_id_c5932b4c_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_featured_image_id_c5932b4c_fk_media_node_id" IMMEDIATE;
--
-- Add field folder to payment
--
ALTER TABLE "payment" ADD COLUMN "folder_id" integer NULL CONSTRAINT "payment_folder_id_62a4f306_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_folder_id_62a4f306_fk_media_node_id" IMMEDIATE;
--
-- Add field updated_by to payment
--
ALTER TABLE "payment" ADD COLUMN "updated_by_id" bigint NOT NULL CONSTRAINT "payment_updated_by_id_5c13b476_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "payment_updated_by_id_5c13b476_fk_users_user_id" IMMEDIATE;
ALTER TABLE "comment" ADD CONSTRAINT "comment_created_by_id_07b197aa_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "comment" ADD CONSTRAINT "comment_updated_by_id_2b05beed_fk_users_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "comment_created_by_id_07b197aa" ON "comment" ("created_by_id");
CREATE INDEX "comment_updated_by_id_2b05beed" ON "comment" ("updated_by_id");
ALTER TABLE "payment_comments" ADD CONSTRAINT "payment_comments_payment_id_comment_id_6230a770_uniq" UNIQUE ("payment_id", "comment_id");
ALTER TABLE "payment_comments" ADD CONSTRAINT "payment_comments_payment_id_dcd1aeaf_fk_payment_id" FOREIGN KEY ("payment_id") REFERENCES "payment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "payment_comments" ADD CONSTRAINT "payment_comments_comment_id_0bd1ef74_fk_comment_id" FOREIGN KEY ("comment_id") REFERENCES "comment" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "payment_comments_payment_id_dcd1aeaf" ON "payment_comments" ("payment_id");
CREATE INDEX "payment_comments_comment_id_0bd1ef74" ON "payment_comments" ("comment_id");
ALTER TABLE "product" ADD CONSTRAINT "product_created_by_id_0baf418a_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product" ADD CONSTRAINT "product_featured_document_id_d27ec0ca_fk_media_node_id" FOREIGN KEY ("featured_document_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product" ADD CONSTRAINT "product_featured_image_id_9f78bcb0_fk_media_node_id" FOREIGN KEY ("featured_image_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product" ADD CONSTRAINT "product_folder_id_3fcf9d26_fk_media_node_id" FOREIGN KEY ("folder_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product" ADD CONSTRAINT "product_payment_id_570693bd_fk_payment_id" FOREIGN KEY ("payment_id") REFERENCES "payment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "product" ADD CONSTRAINT "product_updated_by_id_f384b7dc_fk_users_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "product_created_by_id_0baf418a" ON "product" ("created_by_id");
CREATE INDEX "product_featured_document_id_d27ec0ca" ON "product" ("featured_document_id");
CREATE INDEX "product_featured_image_id_9f78bcb0" ON "product" ("featured_image_id");
CREATE INDEX "product_folder_id_3fcf9d26" ON "product" ("folder_id");
CREATE INDEX "product_payment_id_570693bd" ON "product" ("payment_id");
CREATE INDEX "product_updated_by_id_f384b7dc" ON "product" ("updated_by_id");
CREATE INDEX "payment_contract_id_4abcd408" ON "payment" ("contract_id");
CREATE INDEX "payment_created_by_id_0a1fb28a" ON "payment" ("created_by_id");
CREATE INDEX "payment_featured_document_id_56f84645" ON "payment" ("featured_document_id");
CREATE INDEX "payment_featured_image_id_c5932b4c" ON "payment" ("featured_image_id");
CREATE INDEX "payment_folder_id_62a4f306" ON "payment" ("folder_id");
CREATE INDEX "payment_updated_by_id_5c13b476" ON "payment" ("updated_by_id");

INSERT INTO
    public.django_content_type (app_label, model)
VALUES
    ('app', 'comment'),
    ('app', 'payment'),
    ('app', 'product');



INSERT INTO public.auth_permission ("name",codename,content_type_id) VALUES
	 ('Can add Comentario','add_comment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'comment'
        )),
	 ('Can change Comentario','change_comment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'comment'
        )),
	 ('Can delete Comentario','delete_comment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'comment'
        )),
	 ('Can view Comentario','view_comment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'comment'
        ));

INSERT INTO public.auth_permission ("name",codename,content_type_id) VALUES
	 ('Can add Pago','add_payment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'payment'
        )),
	 ('Can change Pago','change_payment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'payment'
        )),
	 ('Can delete Pago','delete_payment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'payment'
        )),
	 ('Can view Pago','view_payment',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'payment'
        ));

INSERT INTO public.auth_permission ("name",codename,content_type_id) VALUES
	 ('Can add Producto','add_product',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'product'
        )),
	 ('Can change Pago','change_product',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'product'
        )),
	 ('Can delete Pago','delete_product',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'product'
        )),
	 ('Can view Pago','view_product',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'product'
        ));

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_comment')
select t1.id, t2.id
from t1,t2;

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_payment')
select t1.id, t2.id
from t1,t2;

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_product')
select t1.id, t2.id
from t1,t2;

COMMIT;
