-- Deploy sepraps:create_table_amendment to pg

BEGIN;

CREATE TABLE "amendment" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "active" boolean NOT NULL, "signature_date" date NOT NULL, "amendment_type" varchar(50) NOT NULL, "extra_amount" numeric(20, 2) NULL, "extra_period" integer NULL, "contract_id" integer NOT NULL, "created_by_id" bigint NOT NULL, "featured_document_id" integer NULL, "featured_image_id" integer NULL, "folder_id" integer NULL, "updated_by_id" bigint NOT NULL);
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_contract_id_e564a914_fk_construction_contract_id" FOREIGN KEY ("contract_id") REFERENCES "construction_contract" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_created_by_id_6defd523_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_featured_document_id_13d5258f_fk_media_node_id" FOREIGN KEY ("featured_document_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_featured_image_id_fd19cc1c_fk_media_node_id" FOREIGN KEY ("featured_image_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_folder_id_53bb30d0_fk_media_node_id" FOREIGN KEY ("folder_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "amendment" ADD CONSTRAINT "amendment_updated_by_id_c3640f18_fk_users_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "amendment_contract_id_e564a914" ON "amendment" ("contract_id");
CREATE INDEX "amendment_created_by_id_6defd523" ON "amendment" ("created_by_id");
CREATE INDEX "amendment_featured_document_id_13d5258f" ON "amendment" ("featured_document_id");
CREATE INDEX "amendment_featured_image_id_fd19cc1c" ON "amendment" ("featured_image_id");
CREATE INDEX "amendment_folder_id_53bb30d0" ON "amendment" ("folder_id");
CREATE INDEX "amendment_updated_by_id_c3640f18" ON "amendment" ("updated_by_id");

COMMIT;
