-- Deploy sepraps:create_tables_phase2 to pg

BEGIN;

--
-- Create model FieldReport
--
CREATE TABLE "field_report" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "name" varchar(200) NOT NULL, "code" varchar(50) NOT NULL, "date" date NOT NULL, "visit_date_start" date NULL, "visit_date_end" date NULL, "reporting_person" varchar(200) NOT NULL, "reported_persons" varchar(200)[] NOT NULL, "participant_persons" varchar(200)[] NOT NULL, "report_comments_start" text NULL, "report_comments_end" text NULL, "goals" text[] NULL, "created_by_id" bigint NOT NULL, "featured_document_id" integer NULL, "featured_image_id" integer NULL, "folder_id" integer NULL, "updated_by_id" bigint NOT NULL);
--
-- Create model FieldReportProject
--
CREATE TABLE "field_report_project" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "history" text NULL, "agreements" text[] NULL, "created_by_id" bigint NOT NULL, "featured_document_id" integer NULL, "featured_image_id" integer NULL, "field_report_id" bigint NULL, "folder_id" integer NULL);
--
-- Create model FieldReportProjectActivity
--
CREATE TABLE "field_report_project_activity" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "title" text NOT NULL, "date" date NOT NULL, "notes" text NULL, "created_by_id" bigint NOT NULL, "featured_document_id" integer NULL, "featured_image_id" integer NULL, "field_report_project_id" bigint NULL, "folder_id" integer NULL, "image1_id" integer NULL, "image2_id" integer NULL, "image3_id" integer NULL, "image4_id" integer NULL, "updated_by_id" bigint NOT NULL);

--
-- Change Meta options on provider
--
-- (no-op)
--
-- Remove field locality from provider
--
SET CONSTRAINTS "provider_locality_id_d1ba5c1e_fk_locality_code" IMMEDIATE; ALTER TABLE "provider" DROP CONSTRAINT "provider_locality_id_d1ba5c1e_fk_locality_code";
ALTER TABLE "provider" DROP COLUMN "locality_id" CASCADE;
--
-- Add field ci_number to contact
--
ALTER TABLE "contact" ADD COLUMN "ci_number" integer NULL;
--
-- Add field created_at to provider
--
ALTER TABLE "provider" ADD COLUMN "created_at" timestamp with time zone DEFAULT '2023-09-25 15:49:06.080296+00:00'::timestamptz NULL;
ALTER TABLE "provider" ALTER COLUMN "created_at" DROP DEFAULT;
--
-- Add field created_by to provider
--
ALTER TABLE "provider" ADD COLUMN "created_by_id" bigint DEFAULT 1 NOT NULL CONSTRAINT "provider_created_by_id_83cfd2c2_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "provider_created_by_id_83cfd2c2_fk_users_user_id" IMMEDIATE;
ALTER TABLE "provider" ALTER COLUMN "created_by_id" DROP DEFAULT;
--
-- Add field featured_document to provider
--
ALTER TABLE "provider" ADD COLUMN "featured_document_id" integer NULL CONSTRAINT "provider_featured_document_id_f455119a_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "provider_featured_document_id_f455119a_fk_media_node_id" IMMEDIATE;
--
-- Add field featured_image to provider
--
ALTER TABLE "provider" ADD COLUMN "featured_image_id" integer NULL CONSTRAINT "provider_featured_image_id_e3ee84fa_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "provider_featured_image_id_e3ee84fa_fk_media_node_id" IMMEDIATE;
--
-- Add field folder to provider
--
ALTER TABLE "provider" ADD COLUMN "folder_id" integer NULL CONSTRAINT "provider_folder_id_93cefaee_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "provider_folder_id_93cefaee_fk_media_node_id" IMMEDIATE;
--
-- Add field is_legalized to provider
--
ALTER TABLE "provider" ADD COLUMN "is_legalized" boolean DEFAULT false NULL;
ALTER TABLE "provider" ALTER COLUMN "is_legalized" DROP DEFAULT;
--
-- Add field is_provider_contract_signed to provider
--
ALTER TABLE "provider" ADD COLUMN "is_provider_contract_signed" boolean DEFAULT false NULL;
ALTER TABLE "provider" ALTER COLUMN "is_provider_contract_signed" DROP DEFAULT;
--
-- Add field legal_status_number to provider
--
ALTER TABLE "provider" ADD COLUMN "legal_status_number" varchar(20) NULL;
--
-- Add field legalization_date to provider
--
ALTER TABLE "provider" ADD COLUMN "legalization_date" date NULL;
--
-- Add field local_resolution_number to provider
--
ALTER TABLE "provider" ADD COLUMN "local_resolution_number" varchar(20) NULL;
--
-- Add field number_of_members to provider
--
ALTER TABLE "provider" ADD COLUMN "number_of_members" integer NULL;
--
-- Add field number_of_women to provider
--
ALTER TABLE "provider" ADD COLUMN "number_of_women" integer NULL;
--
-- Add field type to provider
--
ALTER TABLE "provider" ADD COLUMN "type" varchar(50) NULL;
--
-- Add field updated_at to provider
--
ALTER TABLE "provider" ADD COLUMN "updated_at" timestamp with time zone DEFAULT '2023-09-25 15:49:06.249903+00:00'::timestamptz NULL;
ALTER TABLE "provider" ALTER COLUMN "updated_at" DROP DEFAULT;
--
-- Add field updated_by to provider
--
ALTER TABLE "provider" ADD COLUMN "updated_by_id" bigint DEFAULT 1 NOT NULL CONSTRAINT "provider_updated_by_id_bff7e2e8_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "provider_updated_by_id_bff7e2e8_fk_users_user_id" IMMEDIATE;
ALTER TABLE "provider" ALTER COLUMN "updated_by_id" DROP DEFAULT;
--
-- Alter field comments on contact
--
ALTER TABLE "contact" ALTER COLUMN "comments" DROP NOT NULL;
--
-- Alter field email on contact
--
ALTER TABLE "contact" ALTER COLUMN "email" DROP NOT NULL;
--
-- Alter field gender on contact
--
-- (no-op)
--
-- Alter field phone on contact
--
ALTER TABLE "contact" ALTER COLUMN "phone" DROP NOT NULL;
--
-- Alter field provider on project
--
-- (no-op)
--
-- Alter field area on provider
--
ALTER TABLE "provider" ALTER COLUMN "area" SET DEFAULT 'rural';
UPDATE "provider" SET "area" = 'rural' WHERE "area" IS NULL; SET CONSTRAINTS ALL IMMEDIATE;
ALTER TABLE "provider" ALTER COLUMN "area" SET NOT NULL;
ALTER TABLE "provider" ALTER COLUMN "area" DROP DEFAULT;
--
-- Alter field id on provider
--
SET CONSTRAINTS "project_provider_id_c9e0bf5d_fk_provider_id" IMMEDIATE; ALTER TABLE "project" DROP CONSTRAINT "project_provider_id_c9e0bf5d_fk_provider_id";
SET CONSTRAINTS "provider_contact_entity_id_879cd13b_fk_provider_id" IMMEDIATE; ALTER TABLE "provider_contact" DROP CONSTRAINT "provider_contact_entity_id_879cd13b_fk_provider_id";
ALTER TABLE "provider" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "provider_id_seq" AS bigint;
ALTER TABLE "project" ALTER COLUMN "provider_id" TYPE bigint USING "provider_id"::bigint;
ALTER TABLE "provider_contact" ALTER COLUMN "entity_id" TYPE bigint USING "entity_id"::bigint;
ALTER TABLE "project" ADD CONSTRAINT "project_provider_id_c9e0bf5d_fk" FOREIGN KEY ("provider_id") REFERENCES "provider" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "provider_contact" ADD CONSTRAINT "provider_contact_entity_id_879cd13b_fk" FOREIGN KEY ("entity_id") REFERENCES "provider" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field name on provider
--
ALTER TABLE "provider" ALTER COLUMN "name" SET NOT NULL;
--
-- Add field project to fieldreportproject
--
ALTER TABLE "field_report_project" ADD COLUMN "project_id" integer NULL CONSTRAINT "field_report_project_project_id_0951d644_fk_project_id" REFERENCES "project"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "field_report_project_project_id_0951d644_fk_project_id" IMMEDIATE;
--
-- Add field updated_by to fieldreportproject
--
ALTER TABLE "field_report_project" ADD COLUMN "updated_by_id" bigint NOT NULL CONSTRAINT "field_report_project_updated_by_id_70a59136_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "field_report_project_updated_by_id_70a59136_fk_users_user_id" IMMEDIATE;
ALTER TABLE "field_report" ADD CONSTRAINT "field_report_created_by_id_1efb5433_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report" ADD CONSTRAINT "field_report_featured_document_id_8aff5a87_fk_media_node_id" FOREIGN KEY ("featured_document_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report" ADD CONSTRAINT "field_report_featured_image_id_ecf8caf8_fk_media_node_id" FOREIGN KEY ("featured_image_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report" ADD CONSTRAINT "field_report_folder_id_b2a4d4c2_fk_media_node_id" FOREIGN KEY ("folder_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report" ADD CONSTRAINT "field_report_updated_by_id_6cbf1e97_fk_users_user_id" FOREIGN KEY ("updated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "field_report_created_by_id_1efb5433" ON "field_report" ("created_by_id");
CREATE INDEX "field_report_featured_document_id_8aff5a87" ON "field_report" ("featured_document_id");
CREATE INDEX "field_report_featured_image_id_ecf8caf8" ON "field_report" ("featured_image_id");
CREATE INDEX "field_report_folder_id_b2a4d4c2" ON "field_report" ("folder_id");
CREATE INDEX "field_report_updated_by_id_6cbf1e97" ON "field_report" ("updated_by_id");
ALTER TABLE "field_report_project" ADD CONSTRAINT "field_report_project_created_by_id_c837eee3_fk_users_user_id" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project" ADD CONSTRAINT "field_report_project_featured_document_id_dba75162_fk_media_nod" FOREIGN KEY ("featured_document_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project" ADD CONSTRAINT "field_report_project_featured_image_id_c21c2003_fk_media_nod" FOREIGN KEY ("featured_image_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project" ADD CONSTRAINT "field_report_project_field_report_id_a6e3ae18_fk_field_rep" FOREIGN KEY ("field_report_id") REFERENCES "field_report" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project" ADD CONSTRAINT "field_report_project_folder_id_27f8a572_fk_media_node_id" FOREIGN KEY ("folder_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "field_report_project_created_by_id_c837eee3" ON "field_report_project" ("created_by_id");
CREATE INDEX "field_report_project_featured_document_id_dba75162" ON "field_report_project" ("featured_document_id");
CREATE INDEX "field_report_project_featured_image_id_c21c2003" ON "field_report_project" ("featured_image_id");
CREATE INDEX "field_report_project_field_report_id_a6e3ae18" ON "field_report_project" ("field_report_id");
CREATE INDEX "field_report_project_folder_id_27f8a572" ON "field_report_project" ("folder_id");
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_created_by_id_d0d4168a_fk_users_use" FOREIGN KEY ("created_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_featured_document_id_be0b22fc_fk_media_nod" FOREIGN KEY ("featured_document_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_featured_image_id_40eb9b45_fk_media_nod" FOREIGN KEY ("featured_image_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_field_report_project_83741948_fk_field_rep" FOREIGN KEY ("field_report_project_id") REFERENCES "field_report_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_folder_id_0039dcb5_fk_media_nod" FOREIGN KEY ("folder_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_image1_id_3770f0f3_fk_media_nod" FOREIGN KEY ("image1_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_image2_id_23049dad_fk_media_nod" FOREIGN KEY ("image2_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_image3_id_c0dca003_fk_media_nod" FOREIGN KEY ("image3_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_image4_id_abda0995_fk_media_nod" FOREIGN KEY ("image4_id") REFERENCES "media_node" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "field_report_project_activity" ADD CONSTRAINT "field_report_project_updated_by_id_37103d04_fk_users_use" FOREIGN KEY ("updated_by_id") REFERENCES "users_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "field_report_project_activity_created_by_id_d0d4168a" ON "field_report_project_activity" ("created_by_id");
CREATE INDEX "field_report_project_activity_featured_document_id_be0b22fc" ON "field_report_project_activity" ("featured_document_id");
CREATE INDEX "field_report_project_activity_featured_image_id_40eb9b45" ON "field_report_project_activity" ("featured_image_id");
CREATE INDEX "field_report_project_activity_field_report_project_id_83741948" ON "field_report_project_activity" ("field_report_project_id");
CREATE INDEX "field_report_project_activity_folder_id_0039dcb5" ON "field_report_project_activity" ("folder_id");
CREATE INDEX "field_report_project_activity_image1_id_3770f0f3" ON "field_report_project_activity" ("image1_id");
CREATE INDEX "field_report_project_activity_image2_id_23049dad" ON "field_report_project_activity" ("image2_id");
CREATE INDEX "field_report_project_activity_image3_id_c0dca003" ON "field_report_project_activity" ("image3_id");
CREATE INDEX "field_report_project_activity_image4_id_abda0995" ON "field_report_project_activity" ("image4_id");
CREATE INDEX "field_report_project_activity_updated_by_id_37103d04" ON "field_report_project_activity" ("updated_by_id");
CREATE INDEX "provider_created_by_id_83cfd2c2" ON "provider" ("created_by_id");
CREATE INDEX "provider_featured_document_id_f455119a" ON "provider" ("featured_document_id");
CREATE INDEX "provider_featured_image_id_e3ee84fa" ON "provider" ("featured_image_id");
CREATE INDEX "provider_folder_id_93cefaee" ON "provider" ("folder_id");
CREATE INDEX "provider_updated_by_id_bff7e2e8" ON "provider" ("updated_by_id");
CREATE INDEX "field_report_project_project_id_0951d644" ON "field_report_project" ("project_id");
CREATE INDEX "field_report_project_updated_by_id_70a59136" ON "field_report_project" ("updated_by_id");



INSERT INTO
    public.django_content_type (app_label, model)
VALUES
    ('app', 'field_report'),
    ('app', 'field_report_project'),
    ('app', 'field_report_project_activity');

INSERT INTO public.auth_permission ("name",codename,content_type_id) VALUES
	 ('Can add Actividad de proyecto en informe de viaje','add_fieldreportprojectactivity',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project_activity'
        )),
	 ('Can change Actividad de proyecto en informe de viaje','change_fieldreportprojectactivity',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project_activity'
        )),
	 ('Can delete Actividad de proyecto en informe de viaje','delete_fieldreportprojectactivity',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project_activity'
        )),
	 ('Can view Actividad de proyecto en informe de viaje','view_fieldreportprojectactivity',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project_activity'
        )),
	 ('Can add Proyecto en informe de viaje','add_fieldreportproject',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project'
        )),
	 ('Can change Proyecto en informe de viaje','change_fieldreportproject',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project'
        )),
	 ('Can delete Proyecto en informe de viaje','delete_fieldreportproject',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project'
        )),
	 ('Can view Proyecto en informe de viaje','view_fieldreportproject',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report_project'
        )),
	 ('Can add Informe de viaje','add_fieldreport',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report'
        )),
	 ('Can change Informe de viaje','change_fieldreport',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report'
        ));
INSERT INTO public.auth_permission ("name",codename,content_type_id) VALUES
	 ('Can delete Informe de viaje','delete_fieldreport',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report'
        )),
	 ('Can view Informe de viaje','view_fieldreport',(
            SELECT
                id
            FROM
                django_content_type
            where
                app_label = 'app'
                AND model = 'field_report'
        ));

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_fieldreport')
select t1.id, t2.id
from t1,t2;

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_fieldreportproject')
select t1.id, t2.id
from t1,t2;

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" in ('edicion', 'gestion', 'supervision')),
	t2 AS (select id from auth_permission p where p.codename like '%_fieldreportprojectactivity')
select t1.id, t2.id
from t1,t2;

INSERT INTO auth_group_permissions (group_id, permission_id)
WITH
	t1 AS (select id from auth_group g where g."name" = 'visualizacion'),
	t2 AS (select id from auth_permission p where p.codename in('view_fieldreport', 'view_fieldreportproject', 'view_fieldreportprojectactivity'))
select t1.id, t2.id
from t1,t2;

COMMIT;
