-- Deploy sepraps:create_table_project_works to pg

BEGIN;


-- Create table project work
CREATE TABLE "project_work" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "work_type" varchar(50) NULL, "work_class" varchar(50) NULL, "project_id" integer NOT NULL);
ALTER TABLE "project_work" ADD CONSTRAINT "project_work_project_id_22035f83_fk_project_id" FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "project_work_project_id_22035f83" ON "project_work" ("project_id");

-- Migrate current project works
INSERT INTO project_work
(
	work_type,
	work_class,
	project_id
)
(
	SELECT
		p.project_type,
		p.project_class,
		p.id
	FROM project p
);

-- Alter project table removing project class and project type
--
ALTER TABLE "project" DROP COLUMN "project_class" CASCADE;
--
-- Remove field project_type from project
--
ALTER TABLE "project" DROP COLUMN "project_type" CASCADE;

COMMIT;
