-- Deploy sepraps:create_tables_services_areas to pg

BEGIN;

ALTER TABLE dominios ALTER COLUMN category TYPE varchar(50);

--
-- Create model ContractService
--
CREATE TABLE "contract_service" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "active" boolean NOT NULL, "code" varchar(50) NOT NULL, "name" varchar(255) NOT NULL, "supervision_areas" varchar(50)[] NOT NULL, "properties" jsonb NULL);
--
-- Remove field execution_final_delivery_date from constructioncontract
--
ALTER TABLE "construction_contract" DROP COLUMN "execution_final_delivery_date" CASCADE;
--
-- Add field services to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "services" varchar(50)[] DEFAULT '{ejecucion_de_obra}' NOT NULL;
ALTER TABLE "construction_contract" ALTER COLUMN "services" DROP DEFAULT;
--
-- Add field updated_by to constructioncontract
--
ALTER TABLE "construction_contract" ADD COLUMN "updated_by_id" bigint DEFAULT 1 NOT NULL CONSTRAINT "construction_contract_updated_by_id_49fa99af_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "construction_contract_updated_by_id_49fa99af_fk_users_user_id" IMMEDIATE;
ALTER TABLE "construction_contract" ALTER COLUMN "updated_by_id" DROP DEFAULT;
--
-- Alter field creation_user on constructioncontract
--
-- (no-op)
--
-- Alter field contract on payment
--
-- (no-op)
--
-- Create model ContractSupervisionArea
--
CREATE TABLE "contract_supervision_area" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "area" varchar(20) NOT NULL, "staff" varchar(50)[] NOT NULL, "contract_id" integer NOT NULL);
--
-- Create model ContractServiceValue
--
CREATE TABLE "contract_service_value" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(50) NOT NULL, "value" text NULL, "contract_service_id" integer NULL);
--
-- Add field contract to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "contract_id" integer NOT NULL CONSTRAINT "contract_service_contract_id_a606bbb0_fk_construct" REFERENCES "construction_contract"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_contract_id_a606bbb0_fk_construct" IMMEDIATE;
--
-- Add field created_by to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "created_by_id" bigint NOT NULL CONSTRAINT "contract_service_created_by_id_d87032da_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_created_by_id_d87032da_fk_users_user_id" IMMEDIATE;
--
-- Add field featured_document to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "featured_document_id" integer NULL CONSTRAINT "contract_service_featured_document_id_f2d9df1e_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_featured_document_id_f2d9df1e_fk_media_node_id" IMMEDIATE;
--
-- Add field featured_image to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "featured_image_id" integer NULL CONSTRAINT "contract_service_featured_image_id_7c615698_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_featured_image_id_7c615698_fk_media_node_id" IMMEDIATE;
--
-- Add field folder to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "folder_id" integer NULL CONSTRAINT "contract_service_folder_id_c126c1b1_fk_media_node_id" REFERENCES "media_node"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_folder_id_c126c1b1_fk_media_node_id" IMMEDIATE;
--
-- Add field updated_by to contractservice
--
ALTER TABLE "contract_service" ADD COLUMN "updated_by_id" bigint NOT NULL CONSTRAINT "contract_service_updated_by_id_bb0fe9b4_fk_users_user_id" REFERENCES "users_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "contract_service_updated_by_id_bb0fe9b4_fk_users_user_id" IMMEDIATE;
CREATE INDEX "construction_contract_updated_by_id_49fa99af" ON "construction_contract" ("updated_by_id");
ALTER TABLE "contract_supervision_area" ADD CONSTRAINT "contract_supervision_contract_id_c981e497_fk_construct" FOREIGN KEY ("contract_id") REFERENCES "construction_contract" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contract_supervision_area_contract_id_c981e497" ON "contract_supervision_area" ("contract_id");
ALTER TABLE "contract_service_value" ADD CONSTRAINT "contract_service_val_contract_service_id_8a83d7fb_fk_contract_" FOREIGN KEY ("contract_service_id") REFERENCES "contract_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contract_service_value_contract_service_id_8a83d7fb" ON "contract_service_value" ("contract_service_id");
CREATE INDEX "contract_service_contract_id_a606bbb0" ON "contract_service" ("contract_id");
CREATE INDEX "contract_service_created_by_id_d87032da" ON "contract_service" ("created_by_id");
CREATE INDEX "contract_service_featured_document_id_f2d9df1e" ON "contract_service" ("featured_document_id");
CREATE INDEX "contract_service_featured_image_id_7c615698" ON "contract_service" ("featured_image_id");
CREATE INDEX "contract_service_folder_id_c126c1b1" ON "contract_service" ("folder_id");
CREATE INDEX "contract_service_updated_by_id_bb0fe9b4" ON "contract_service" ("updated_by_id");

INSERT INTO contract_service
(created_at, updated_at, active, code, "name", supervision_areas, properties, contract_id, created_by_id, featured_document_id, featured_image_id, folder_id, updated_by_id)
SELECT
	now(),
	now(),
	true,
	'ejecucion_de_obra',
	'Ejecución de obra',
	'{building,social}',
	'{"finalDeliveryDate": {"type": "date", "label": "Fecha de recepción definitiva", "order": 2}, "executionCertificateDate": {"type": "date", "label": "Fecha del acta de inicio", "order": 1}}'::jsonb,
	cc.id,
	1, NULL, NULL, NULL, 1
FROM construction_contract cc;

INSERT INTO
contract_service_value (code,value,contract_service_id)
SELECT
	unnest(array['executionCertificateDate', 'finalDeliveryDate']),
	null,
	cs.id
FROM contract_service cs;

INSERT INTO contract_supervision_area
(area, staff, contract_id)
SELECT
	unnest(array['building', 'social']),
	array[]::varchar[],
	cc.id
FROM construction_contract cc;


INSERT INTO public.media_node
(media_type, media_name, storage_path, created_at, creation_user_id)
SELECT
	'FOLDER',
	'ContractService_' || cs.id,
	'contractservice/' || cs.id,
	now(),
	1
FROM contract_service cs;

UPDATE contract_service cs
SET folder_id = mn.id
FROM media_node mn where mn.storage_path = 'contractservice/' || cs.id;


COMMIT;
